import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Login from "./auth/Login";

const Home: NextPage = () => {
   return (
      <div className="bg-zinc-700 text-white">
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <Login />
         </main>
      </div>
   );
};

export default Home;
